export const SQL_INIT_SCHEMA = `
CREATE TABLE IF NOT EXISTS config (
  id TEXT PRIMARY KEY,
  nome_fantasia TEXT NOT NULL,
  razao_social TEXT,
  cnpj TEXT,
  telefone TEXT,
  endereco TEXT,
  mensagem_cupom TEXT,
  supabase_url TEXT,
  supabase_anon_key TEXT,
  supabase_ativo INTEGER DEFAULT 0,
  ultimo_backup_at TEXT
);

CREATE TABLE IF NOT EXISTS produtos (
  id TEXT PRIMARY KEY,
  codigo_barras TEXT,
  nome TEXT NOT NULL,
  descricao TEXT,
  preco_custo REAL DEFAULT 0,
  preco_venda REAL NOT NULL,
  estoque_atual REAL DEFAULT 0,
  estoque_minimo REAL DEFAULT 0,
  unidade_medida TEXT DEFAULT 'UN',
  categoria TEXT DEFAULT 'Geral',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  deleted_at TEXT,
  sync_status TEXT DEFAULT 'pending'
);

CREATE TABLE IF NOT EXISTS clientes (
  id TEXT PRIMARY KEY,
  nome TEXT NOT NULL,
  documento TEXT,
  telefone TEXT,
  email TEXT,
  endereco TEXT,
  limite_credito REAL DEFAULT 0,
  saldo_devedor REAL DEFAULT 0,
  observacoes TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  deleted_at TEXT,
  sync_status TEXT DEFAULT 'pending'
);

CREATE TABLE IF NOT EXISTS vendas (
  id TEXT PRIMARY KEY,
  numero_venda INTEGER,
  cliente_id TEXT,
  cliente_nome TEXT,
  total_bruto REAL NOT NULL,
  desconto REAL DEFAULT 0,
  total_liquido REAL NOT NULL,
  forma_pagamento TEXT NOT NULL,
  valor_pago REAL,
  troco REAL,
  status TEXT DEFAULT 'concluida',
  observacoes TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  deleted_at TEXT,
  sync_status TEXT DEFAULT 'pending'
);

CREATE TABLE IF NOT EXISTS itens_venda (
  id TEXT PRIMARY KEY,
  venda_id TEXT NOT NULL,
  produto_id TEXT NOT NULL,
  produto_nome TEXT NOT NULL,
  quantidade REAL NOT NULL,
  preco_unitario REAL NOT NULL,
  subtotal REAL NOT NULL,
  created_at TEXT NOT NULL,
  FOREIGN KEY (venda_id) REFERENCES vendas(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS movimentacoes_estoque (
  id TEXT PRIMARY KEY,
  produto_id TEXT NOT NULL,
  produto_nome TEXT NOT NULL,
  tipo TEXT NOT NULL,
  quantidade REAL NOT NULL,
  estoque_anterior REAL NOT NULL,
  estoque_novo REAL NOT NULL,
  motivo TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS caixas (
  id TEXT PRIMARY KEY,
  operador TEXT NOT NULL,
  valor_inicial REAL NOT NULL,
  saldo_esperado REAL,
  saldo_real REAL,
  diferenca REAL,
  status TEXT DEFAULT 'aberto',
  data_abertura TEXT NOT NULL,
  data_fechamento TEXT,
  observacoes TEXT
);

CREATE TABLE IF NOT EXISTS movimentos_caixa (
  id TEXT PRIMARY KEY,
  caixa_id TEXT NOT NULL,
  tipo TEXT NOT NULL,
  valor REAL NOT NULL,
  motivo TEXT,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_produtos_codigo ON produtos(codigo_barras);
CREATE INDEX IF NOT EXISTS idx_produtos_nome ON produtos(nome);
CREATE INDEX IF NOT EXISTS idx_vendas_data ON vendas(created_at);
CREATE INDEX IF NOT EXISTS idx_itens_venda_id ON itens_venda(venda_id);
`;

export const SQL_SUPABASE_POSTGRES_SCHEMA = `
-- Script para rodar no SQL Editor do Supabase para espelhar as tabelas
CREATE TABLE IF NOT EXISTS public.config (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nome_fantasia TEXT NOT NULL,
  razao_social TEXT,
  cnpj TEXT,
  telefone TEXT,
  endereco TEXT,
  mensagem_cupom TEXT,
  ultimo_backup_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.produtos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  codigo_barras TEXT,
  nome TEXT NOT NULL,
  descricao TEXT,
  preco_custo NUMERIC(12,2) DEFAULT 0,
  preco_venda NUMERIC(12,2) NOT NULL,
  estoque_atual NUMERIC(12,3) DEFAULT 0,
  estoque_minimo NUMERIC(12,3) DEFAULT 0,
  unidade_medida VARCHAR(10) DEFAULT 'UN',
  categoria TEXT DEFAULT 'Geral',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.clientes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nome TEXT NOT NULL,
  documento TEXT,
  telefone TEXT,
  email TEXT,
  endereco TEXT,
  limite_credito NUMERIC(12,2) DEFAULT 0,
  saldo_devedor NUMERIC(12,2) DEFAULT 0,
  observacoes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.vendas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  numero_venda BIGINT GENERATED BY DEFAULT AS IDENTITY,
  cliente_id UUID REFERENCES public.clientes(id),
  cliente_nome TEXT,
  total_bruto NUMERIC(12,2) NOT NULL,
  desconto NUMERIC(12,2) DEFAULT 0,
  total_liquido NUMERIC(12,2) NOT NULL,
  forma_pagamento VARCHAR(30) NOT NULL,
  valor_pago NUMERIC(12,2),
  troco NUMERIC(12,2),
  status VARCHAR(20) DEFAULT 'concluida',
  observacoes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.itens_venda (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  venda_id UUID NOT NULL REFERENCES public.vendas(id) ON DELETE CASCADE,
  produto_id UUID NOT NULL REFERENCES public.produtos(id),
  produto_nome TEXT NOT NULL,
  quantidade NUMERIC(12,3) NOT NULL,
  preco_unitario NUMERIC(12,2) NOT NULL,
  subtotal NUMERIC(12,2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Ativação de RLS (Row Level Security) opcional
ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.itens_venda ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso total anon/autenticado" ON public.produtos FOR ALL USING (true);
CREATE POLICY "Acesso total anon/autenticado" ON public.clientes FOR ALL USING (true);
CREATE POLICY "Acesso total anon/autenticado" ON public.vendas FOR ALL USING (true);
CREATE POLICY "Acesso total anon/autenticado" ON public.itens_venda FOR ALL USING (true);
`;
